### PR TITLE
Windows Compatibility

### PR DESCRIPTION
**Pull request by kleblackford**
Problems with windows install are discussed in #99. I have implemented a solution using the registry entries to find the JACK install folder. I have also added/updated a couple of tests. They seem to be passing (except for test_set_output_functions_not_none which I guess was already broken). Some feedback would be good :)

### CODE REVIEW

**Comment by vrslev** [comment]
`winreg` is available on Windows only, so the package won’t work on macOS and Linux 😅 Try importing the module after checking platform.
Also I think we should run tests in CI on Windows

**Comment by kleblackford** [comment]
I refactored the code somewhat to make the implementation a little tidier. 

What is strange is that test_set_output_functions_not_none passes as I step through it when debugging. I suppose something strange to do with the wrapping decorator [here](https://github.com/vrslev/jack_server/blob/03c3faad53e803fd01d734e002595e0508c882c2/src/jack_server/_output.py#L17) is messing things up...

**Comment by vrslev** [comment]
I don't think the `test_get_library_windows_name_found` test is necessary. Too much hassle for a trivial piece code 😅

**Comment by vrslev** [comment]
> What is strange is that test_set_output_functions_not_none passes as I step through it when debugging. I suppose something strange to do with the wrapping decorator [here](https://github.com/vrslev/jack_server/blob/03c3faad53e803fd01d734e002595e0508c882c2/src/jack_server/_output.py#L17) is messing things up...

What the test will output if we change it to this?

```python
def test_set_output_functions_not_none(server: Server):
    def out(m):
        print("out:", m)

    def err(m):
        print("err:", m)

    set_error_function(out)
    set_info_function(err)
    server.start()
```

On my Mac that's what's being printed:

```
tests/test_output.py err: JACK server starting in non-realtime mode
err: self-connect-mode is "Don't restrict self connect requests"
out: Default input and output devices are not the same !!
out: Cannot open default device in duplex mode, so aggregate default input and default output
err: Separated input = 'MacBook Air Microphone' 
err: Separated output = 'MacBook Air Speakers' 
err: Input channel = 0 ==> JACK input port = 0
err: JACK output port = 0 ==> output channel = 0
err: JACK output port = 1 ==> output channel = 1
err: CoreAudio driver is running...
.
```

Can you pull the changes I made and share your output?

**Comment by kleblackford** [comment]
Ah I think the problem is deeper... Here is my test output (after redefining the aforementioned test):

```
(jack-server-py3.11) PS C:\Users\e.blackford\Repositories\jack_server> pytest tests/test_output.py::test_set_output_functions_not_none
=========================================================================================== test session starts ===========================================================================================
platform win32 -- Python 3.11.5, pytest-7.4.3, pluggy-1.3.0
rootdir: C:\Users\e.blackford\Repositories\jack_server     
configfile: pyproject.toml
plugins: cov-4.1.0
collected 1 item

tests\test_output.py Drivers/internals found in : C:\Program Files\JACK2
jack_get_descriptor : dll jack_inprocess.dll is not a driver
jack_get_descriptor returns null for 'jack_inprocess.dll'
jack_get_descriptor : dll jack_internal_metro.dll is not a driver
jack_get_descriptor returns null for 'jack_internal_metro.dll'
jack_get_descriptor : dll jack_intime.dll is not a driver
jack_get_descriptor returns null for 'jack_intime.dll'
Drivers/internals found in : C:\Program Files\JACK2
err: JACK server starting in non-realtime mode
err: self-connect-mode is "Don't restrict self connect requests"
Cannot connect to named pipe after wait = \\.\pipe\server_jack_default_0 err = 2
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Open error: is JACK server running?
jack_deactivate called with a NULL client
jack_deactivate called with a NULL client
jack_client_close called with a NULL client
.

============================================================================================ 1 passed in 0.65s ============================================================================================ 
```

Does this mean anything to you? This is happening for all the tests. I guess I was naive in thinking that as they were passing everything was fine :D

**Comment by vrslev** [comment]
Feel free to reopen if you decide to continue

**Pull request closed without merging**
