### PR TITLE
Add `nperiods` property to `Driver`

### PR DESCRIPTION
**Pull request by hjespersen**
This will just add the possibility to configure the number of periods used by the underlying soundcard. This can be especially helpfull when tailoring performance on jittery systems.

### CODE REVIEW

**Comment by vrslev** [comment]
Hi there! Looks great, can you just add tests? I want to keep coverage at 100%.

**Comment by hjespersen** [comment]
> Hi there! Looks great, can you just add tests? I want to keep coverage at 100%.

hmm. jack2 dummy driver - used in the tests - doesn't allow you to change `nperiods` [JackDummyDriver](https://github.com/jackaudio/jack2/blob/886b35c3bda019a2e83102c0711bbaa475efde7e/common/JackDummyDriver.cpp#L35). Adding tests for `nperiods` would then involve either using `alsa` -driver or change the `JackDummyDriver`

**Comment by vrslev** [comment]
OK, got it. I will see what can be done once I’ll be in front of computer 😃

**Comment by vrslev** [comment]
I don't want to add `alsa` driver in CI, so let's just special case this param 😃

**Comment by vrslev** [comment]
Just released v0.2.0—it includes this PR :)

**Pull request merged**
